# Generated by Django 3.2.6 on 2021-08-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('adjclose', models.DecimalField(decimal_places=16, max_digits=19)),
                ('returntx', models.DecimalField(decimal_places=16, max_digits=19)),
                ('risktx', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
        ),
    ]
