# Generated by Django 3.2.6 on 2021-08-23 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_calculos_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('adjclose', models.DecimalField(decimal_places=16, max_digits=19)),
                ('returntx', models.DecimalField(decimal_places=16, max_digits=19)),
                ('risktx', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='adjclose',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='returntx',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='risktx',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ticker',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='acoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.acoes'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.investidor'),
        ),
    ]
