# Generated by Django 3.2.6 on 2021-08-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210823_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
