# Generated by Django 3.2.6 on 2021-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='adjclose',
            field=models.DecimalField(decimal_places=160, max_digits=190),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='retorno',
            field=models.DecimalField(decimal_places=160, max_digits=190),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='txrisk',
            field=models.DecimalField(decimal_places=160, max_digits=190),
        ),
    ]
