# Generated by Django 3.2.6 on 2021-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210826_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
