# Generated by Django 3.2.7 on 2021-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_acoes_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='adjclose',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='retorno',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='txrisk',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
