# Generated by Django 3.2.7 on 2021-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210927_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='adjclose',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='retorno',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='txrisk',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
