# Generated by Django 3.2.7 on 2021-09-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210927_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='ticker',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
