# Generated by Django 3.2.7 on 2021-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_acoes_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='ticker',
            field=models.CharField(max_length=7),
        ),
    ]
