# Generated by Django 3.2.7 on 2021-09-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_alter_acoes_investidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='investidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=7)),
                ('adjclose', models.DecimalField(decimal_places=2, max_digits=7)),
                ('retorno', models.DecimalField(decimal_places=2, max_digits=7)),
                ('txrisk', models.DecimalField(decimal_places=2, max_digits=7)),
                ('investidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
