# Generated by Django 3.2.7 on 2021-09-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_auto_20210928_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='acoes',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='acao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.acoes', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
